"""Larky's str methods follow CPython where Starlark differs.

Generated with CPython 3.12.14 (Unicode 15.0.0); the expected values are CPython's.
"""
load("@vendor//asserts", "asserts")
load("@stdlib//unittest", "unittest")

# (string, method, sub, start, end, CPython's result): start > end matches nothing, not even "".
_BOUNDS = [
    ("abc", "find", "", 4, None, -1),
    ("abc", "rfind", "", 4, None, -1),
    ("abc", "count", "", 4, None, 0),
    ("abc", "startswith", "", 4, None, False),
    ("abc", "endswith", "", 4, None, False),
    ("abc", "find", "", 7, None, -1),
    ("abc", "rfind", "", 7, None, -1),
    ("abc", "count", "", 7, None, 0),
    ("abc", "startswith", "", 7, None, False),
    ("abc", "endswith", "", 7, None, False),
    ("abc", "find", "", 2, 1, -1),
    ("abc", "rfind", "", 2, 1, -1),
    ("abc", "count", "", 2, 1, 0),
    ("abc", "startswith", "", 2, 1, False),
    ("abc", "endswith", "", 2, 1, False),
    ("abc", "find", "", 5, 10, -1),
    ("abc", "rfind", "", 5, 10, -1),
    ("abc", "count", "", 5, 10, 0),
    ("abc", "startswith", "", 5, 10, False),
    ("abc", "endswith", "", 5, 10, False),
    ("abc", "find", "", 1, -5, -1),
    ("abc", "rfind", "", 1, -5, -1),
    ("abc", "count", "", 1, -5, 0),
    ("abc", "startswith", "", 1, -5, False),
    ("abc", "endswith", "", 1, -5, False),
    ("abc", "find", "", 3, None, 3),
    ("abc", "rfind", "", 3, None, 3),
    ("abc", "count", "", 3, None, 1),
    ("abc", "startswith", "", 3, None, True),
    ("abc", "endswith", "", 3, None, True),
    ("abc", "find", "", 0, -4, 0),
    ("abc", "rfind", "", 0, -4, 0),
    ("abc", "count", "", 0, -4, 1),
    ("abc", "startswith", "", 0, -4, True),
    ("abc", "endswith", "", 0, -4, True),
    ("abc", "find", "c", 4, None, -1),
    ("abc", "rfind", "c", 4, None, -1),
    ("abc", "count", "c", 4, None, 0),
    ("abc", "startswith", "c", 4, None, False),
    ("abc", "endswith", "c", 4, None, False),
    ("abc", "find", "c", 7, None, -1),
    ("abc", "rfind", "c", 7, None, -1),
    ("abc", "count", "c", 7, None, 0),
    ("abc", "startswith", "c", 7, None, False),
    ("abc", "endswith", "c", 7, None, False),
    ("abc", "find", "c", 2, 1, -1),
    ("abc", "rfind", "c", 2, 1, -1),
    ("abc", "count", "c", 2, 1, 0),
    ("abc", "startswith", "c", 2, 1, False),
    ("abc", "endswith", "c", 2, 1, False),
    ("abc", "find", "c", 5, 10, -1),
    ("abc", "rfind", "c", 5, 10, -1),
    ("abc", "count", "c", 5, 10, 0),
    ("abc", "startswith", "c", 5, 10, False),
    ("abc", "endswith", "c", 5, 10, False),
    ("abc", "find", "c", 1, -5, -1),
    ("abc", "rfind", "c", 1, -5, -1),
    ("abc", "count", "c", 1, -5, 0),
    ("abc", "startswith", "c", 1, -5, False),
    ("abc", "endswith", "c", 1, -5, False),
    ("abc", "find", "c", 3, None, -1),
    ("abc", "rfind", "c", 3, None, -1),
    ("abc", "count", "c", 3, None, 0),
    ("abc", "startswith", "c", 3, None, False),
    ("abc", "endswith", "c", 3, None, False),
    ("abc", "find", "c", 0, -4, -1),
    ("abc", "rfind", "c", 0, -4, -1),
    ("abc", "count", "c", 0, -4, 0),
    ("abc", "startswith", "c", 0, -4, False),
    ("abc", "endswith", "c", 0, -4, False),
    ("abcabc", "find", "", 4, None, 4),
    ("abcabc", "rfind", "", 4, None, 6),
    ("abcabc", "count", "", 4, None, 3),
    ("abcabc", "startswith", "", 4, None, True),
    ("abcabc", "endswith", "", 4, None, True),
    ("abcabc", "find", "", 7, None, -1),
    ("abcabc", "rfind", "", 7, None, -1),
    ("abcabc", "count", "", 7, None, 0),
    ("abcabc", "startswith", "", 7, None, False),
    ("abcabc", "endswith", "", 7, None, False),
    ("abcabc", "find", "", 2, 1, -1),
    ("abcabc", "rfind", "", 2, 1, -1),
    ("abcabc", "count", "", 2, 1, 0),
    ("abcabc", "startswith", "", 2, 1, False),
    ("abcabc", "endswith", "", 2, 1, False),
    ("abcabc", "find", "", 5, 10, 5),
    ("abcabc", "rfind", "", 5, 10, 6),
    ("abcabc", "count", "", 5, 10, 2),
    ("abcabc", "startswith", "", 5, 10, True),
    ("abcabc", "endswith", "", 5, 10, True),
    ("abcabc", "find", "", 1, -5, 1),
    ("abcabc", "rfind", "", 1, -5, 1),
    ("abcabc", "count", "", 1, -5, 1),
    ("abcabc", "startswith", "", 1, -5, True),
    ("abcabc", "endswith", "", 1, -5, True),
    ("abcabc", "find", "", 3, None, 3),
    ("abcabc", "rfind", "", 3, None, 6),
    ("abcabc", "count", "", 3, None, 4),
    ("abcabc", "startswith", "", 3, None, True),
    ("abcabc", "endswith", "", 3, None, True),
    ("abcabc", "find", "", 0, -4, 0),
    ("abcabc", "rfind", "", 0, -4, 2),
    ("abcabc", "count", "", 0, -4, 3),
    ("abcabc", "startswith", "", 0, -4, True),
    ("abcabc", "endswith", "", 0, -4, True),
    ("abcabc", "find", "c", 4, None, 5),
    ("abcabc", "rfind", "c", 4, None, 5),
    ("abcabc", "count", "c", 4, None, 1),
    ("abcabc", "startswith", "c", 4, None, False),
    ("abcabc", "endswith", "c", 4, None, True),
    ("abcabc", "find", "c", 7, None, -1),
    ("abcabc", "rfind", "c", 7, None, -1),
    ("abcabc", "count", "c", 7, None, 0),
    ("abcabc", "startswith", "c", 7, None, False),
    ("abcabc", "endswith", "c", 7, None, False),
    ("abcabc", "find", "c", 2, 1, -1),
    ("abcabc", "rfind", "c", 2, 1, -1),
    ("abcabc", "count", "c", 2, 1, 0),
    ("abcabc", "startswith", "c", 2, 1, False),
    ("abcabc", "endswith", "c", 2, 1, False),
    ("abcabc", "find", "c", 5, 10, 5),
    ("abcabc", "rfind", "c", 5, 10, 5),
    ("abcabc", "count", "c", 5, 10, 1),
    ("abcabc", "startswith", "c", 5, 10, True),
    ("abcabc", "endswith", "c", 5, 10, True),
    ("abcabc", "find", "c", 1, -5, -1),
    ("abcabc", "rfind", "c", 1, -5, -1),
    ("abcabc", "count", "c", 1, -5, 0),
    ("abcabc", "startswith", "c", 1, -5, False),
    ("abcabc", "endswith", "c", 1, -5, False),
    ("abcabc", "find", "c", 3, None, 5),
    ("abcabc", "rfind", "c", 3, None, 5),
    ("abcabc", "count", "c", 3, None, 1),
    ("abcabc", "startswith", "c", 3, None, False),
    ("abcabc", "endswith", "c", 3, None, True),
    ("abcabc", "find", "c", 0, -4, -1),
    ("abcabc", "rfind", "c", 0, -4, -1),
    ("abcabc", "count", "c", 0, -4, 0),
    ("abcabc", "startswith", "c", 0, -4, False),
    ("abcabc", "endswith", "c", 0, -4, False),
    ("", "find", "", 4, None, -1),
    ("", "rfind", "", 4, None, -1),
    ("", "count", "", 4, None, 0),
    ("", "startswith", "", 4, None, False),
    ("", "endswith", "", 4, None, False),
    ("", "find", "", 7, None, -1),
    ("", "rfind", "", 7, None, -1),
    ("", "count", "", 7, None, 0),
    ("", "startswith", "", 7, None, False),
    ("", "endswith", "", 7, None, False),
    ("", "find", "", 2, 1, -1),
    ("", "rfind", "", 2, 1, -1),
    ("", "count", "", 2, 1, 0),
    ("", "startswith", "", 2, 1, False),
    ("", "endswith", "", 2, 1, False),
    ("", "find", "", 5, 10, -1),
    ("", "rfind", "", 5, 10, -1),
    ("", "count", "", 5, 10, 0),
    ("", "startswith", "", 5, 10, False),
    ("", "endswith", "", 5, 10, False),
    ("", "find", "", 1, -5, -1),
    ("", "rfind", "", 1, -5, -1),
    ("", "count", "", 1, -5, 0),
    ("", "startswith", "", 1, -5, False),
    ("", "endswith", "", 1, -5, False),
    ("", "find", "", 3, None, -1),
    ("", "rfind", "", 3, None, -1),
    ("", "count", "", 3, None, 0),
    ("", "startswith", "", 3, None, False),
    ("", "endswith", "", 3, None, False),
    ("", "find", "", 0, -4, 0),
    ("", "rfind", "", 0, -4, 0),
    ("", "count", "", 0, -4, 1),
    ("", "startswith", "", 0, -4, True),
    ("", "endswith", "", 0, -4, True),
    ("", "find", "c", 4, None, -1),
    ("", "rfind", "c", 4, None, -1),
    ("", "count", "c", 4, None, 0),
    ("", "startswith", "c", 4, None, False),
    ("", "endswith", "c", 4, None, False),
    ("", "find", "c", 7, None, -1),
    ("", "rfind", "c", 7, None, -1),
    ("", "count", "c", 7, None, 0),
    ("", "startswith", "c", 7, None, False),
    ("", "endswith", "c", 7, None, False),
    ("", "find", "c", 2, 1, -1),
    ("", "rfind", "c", 2, 1, -1),
    ("", "count", "c", 2, 1, 0),
    ("", "startswith", "c", 2, 1, False),
    ("", "endswith", "c", 2, 1, False),
    ("", "find", "c", 5, 10, -1),
    ("", "rfind", "c", 5, 10, -1),
    ("", "count", "c", 5, 10, 0),
    ("", "startswith", "c", 5, 10, False),
    ("", "endswith", "c", 5, 10, False),
    ("", "find", "c", 1, -5, -1),
    ("", "rfind", "c", 1, -5, -1),
    ("", "count", "c", 1, -5, 0),
    ("", "startswith", "c", 1, -5, False),
    ("", "endswith", "c", 1, -5, False),
    ("", "find", "c", 3, None, -1),
    ("", "rfind", "c", 3, None, -1),
    ("", "count", "c", 3, None, 0),
    ("", "startswith", "c", 3, None, False),
    ("", "endswith", "c", 3, None, False),
    ("", "find", "c", 0, -4, -1),
    ("", "rfind", "c", 0, -4, -1),
    ("", "count", "c", 0, -4, 0),
    ("", "startswith", "c", 0, -4, False),
    ("", "endswith", "c", 0, -4, False),
]


def _test_bounds():
    for s, method, sub, start, end, want in _BOUNDS:
        got = getattr(s, method)(sub, start, end)
        asserts.assert_that(got).is_equal_to(want)
    asserts.assert_fails(lambda: "abc".index("", 4), "substring not found")
    asserts.assert_fails(lambda: "abc".rindex("", 2, 1), "substring not found")
    asserts.assert_that("abc".startswith(("x", ""), 4)).is_false()


# (string, method, CPython's result)
_UNICODE = [
    ("été €", "upper", "ÉTÉ €"),
    ("été €", "lower", "été €"),
    ("été €", "title", "Été €"),
    ("été €", "capitalize", "Été €"),
    ("ß", "upper", "SS"),
    ("ß", "lower", "ß"),
    ("ß", "title", "Ss"),
    ("ß", "capitalize", "Ss"),
    ("ﬁ", "upper", "FI"),
    ("ﬁ", "lower", "ﬁ"),
    ("ﬁ", "title", "Fi"),
    ("ﬁ", "capitalize", "Fi"),
    ("ı", "upper", "I"),
    ("ı", "lower", "ı"),
    ("ı", "title", "I"),
    ("ı", "capitalize", "I"),
    ("İ", "upper", "İ"),
    ("İ", "lower", "i\u0307"),
    ("İ", "title", "İ"),
    ("İ", "capitalize", "İ"),
    ("ΣΣ", "upper", "ΣΣ"),
    ("ΣΣ", "lower", "σς"),
    ("ΣΣ", "title", "Σς"),
    ("ΣΣ", "capitalize", "Σς"),
    ("ẞ", "upper", "ẞ"),
    ("ẞ", "lower", "ß"),
    ("ẞ", "title", "ẞ"),
    ("ẞ", "capitalize", "ẞ"),
    ("ΑΣ ΣΑ", "upper", "ΑΣ ΣΑ"),
    ("ΑΣ ΣΑ", "lower", "ας σα"),
    ("ΑΣ ΣΑ", "title", "Ας Σα"),
    ("ΑΣ ΣΑ", "capitalize", "Ας σα"),
    ("ǆenan", "upper", "ǄENAN"),
    ("ǆenan", "lower", "ǆenan"),
    ("ǆenan", "title", "ǅenan"),
    ("ǆenan", "capitalize", "ǅenan"),
    ("ŉ", "upper", "ʼN"),
    ("ŉ", "lower", "ŉ"),
    ("ŉ", "title", "ʼN"),
    ("ŉ", "capitalize", "ʼN"),
    ("Straße", "upper", "STRASSE"),
    ("Straße", "lower", "straße"),
    ("Straße", "title", "Straße"),
    ("Straße", "capitalize", "Straße"),
    ("ÉCOLE", "upper", "ÉCOLE"),
    ("ÉCOLE", "lower", "école"),
    ("ÉCOLE", "title", "École"),
    ("ÉCOLE", "capitalize", "École"),
    ("ﬁre ßtraße", "upper", "FIRE SSTRASSE"),
    ("ﬁre ßtraße", "lower", "ﬁre ßtraße"),
    ("ﬁre ßtraße", "title", "Fire Sstraße"),
    ("ﬁre ßtraße", "capitalize", "Fire ßtraße"),
    ("A'Σb", "upper", "A'ΣB"),
    ("A'Σb", "lower", "a'σb"),
    ("A'Σb", "title", "A'Σb"),
    ("A'Σb", "capitalize", "A'σb"),
    ("𐐀", "upper", "𐐀"),
    ("𐐀", "lower", "𐐨"),
    ("𐐀", "title", "𐐀"),
    ("𐐀", "capitalize", "𐐀"),
    ("ǅ", "upper", "Ǆ"),
    ("ǅ", "lower", "ǆ"),
    ("ǅ", "title", "ǅ"),
    ("ǅ", "capitalize", "ǅ"),
    ("é", "isalpha", True),
    ("é", "isalnum", True),
    ("é", "isdigit", False),
    ("é", "isspace", False),
    ("é", "islower", True),
    ("é", "isupper", False),
    ("é", "istitle", False),
    ("²", "isalpha", False),
    ("²", "isalnum", True),
    ("²", "isdigit", True),
    ("²", "isspace", False),
    ("²", "islower", False),
    ("²", "isupper", False),
    ("²", "istitle", False),
    ("①", "isalpha", False),
    ("①", "isalnum", True),
    ("①", "isdigit", True),
    ("①", "isspace", False),
    ("①", "islower", False),
    ("①", "isupper", False),
    ("①", "istitle", False),
    ("٣", "isalpha", False),
    ("٣", "isalnum", True),
    ("٣", "isdigit", True),
    ("٣", "isspace", False),
    ("٣", "islower", False),
    ("٣", "isupper", False),
    ("٣", "istitle", False),
    ("½", "isalpha", False),
    ("½", "isalnum", True),
    ("½", "isdigit", False),
    ("½", "isspace", False),
    ("½", "islower", False),
    ("½", "isupper", False),
    ("½", "istitle", False),
    ("\u3000", "isalpha", False),
    ("\u3000", "isalnum", False),
    ("\u3000", "isdigit", False),
    ("\u3000", "isspace", True),
    ("\u3000", "islower", False),
    ("\u3000", "isupper", False),
    ("\u3000", "istitle", False),
    ("\x1c", "isalpha", False),
    ("\x1c", "isalnum", False),
    ("\x1c", "isdigit", False),
    ("\x1c", "isspace", True),
    ("\x1c", "islower", False),
    ("\x1c", "isupper", False),
    ("\x1c", "istitle", False),
    ("\u200b", "isalpha", False),
    ("\u200b", "isalnum", False),
    ("\u200b", "isdigit", False),
    ("\u200b", "isspace", False),
    ("\u200b", "islower", False),
    ("\u200b", "isupper", False),
    ("\u200b", "istitle", False),
    ("ǅ", "isalpha", True),
    ("ǅ", "isalnum", True),
    ("ǅ", "isdigit", False),
    ("ǅ", "isspace", False),
    ("ǅ", "islower", False),
    ("ǅ", "isupper", False),
    ("ǅ", "istitle", True),
    ("Ǆa", "isalpha", True),
    ("Ǆa", "isalnum", True),
    ("Ǆa", "isdigit", False),
    ("Ǆa", "isspace", False),
    ("Ǆa", "islower", False),
    ("Ǆa", "isupper", False),
    ("Ǆa", "istitle", True),
    ("ⓐ", "isalpha", False),
    ("ⓐ", "isalnum", False),
    ("ⓐ", "isdigit", False),
    ("ⓐ", "isspace", False),
    ("ⓐ", "islower", True),
    ("ⓐ", "isupper", False),
    ("ⓐ", "istitle", False),
    ("ª", "isalpha", True),
    ("ª", "isalnum", True),
    ("ª", "isdigit", False),
    ("ª", "isspace", False),
    ("ª", "islower", True),
    ("ª", "isupper", False),
    ("ª", "istitle", False),
    ("é1", "isalpha", False),
    ("é1", "isalnum", True),
    ("é1", "isdigit", False),
    ("é1", "isspace", False),
    ("é1", "islower", True),
    ("é1", "isupper", False),
    ("é1", "istitle", False),
    ("É", "isalpha", True),
    ("É", "isalnum", True),
    ("É", "isdigit", False),
    ("É", "isspace", False),
    ("É", "islower", False),
    ("É", "isupper", True),
    ("É", "istitle", True),
    ("élan", "isalpha", True),
    ("élan", "isalnum", True),
    ("élan", "isdigit", False),
    ("élan", "isspace", False),
    ("élan", "islower", True),
    ("élan", "isupper", False),
    ("élan", "istitle", False),
    ("Élan", "isalpha", True),
    ("Élan", "isalnum", True),
    ("Élan", "isdigit", False),
    ("Élan", "isspace", False),
    ("Élan", "islower", False),
    ("Élan", "isupper", False),
    ("Élan", "istitle", True),
    ("\u3000x\u2000", "strip", "x"),
    ("\x1c x\x1f", "strip", "x"),
]


def _test_unicode():
    for s, method, want in _UNICODE:
        got = getattr(s, method)()
        asserts.assert_that(got).is_equal_to(want)


def _suite():
    _suite = unittest.TestSuite()
    _suite.addTest(unittest.FunctionTestCase(_test_bounds))
    _suite.addTest(unittest.FunctionTestCase(_test_unicode))
    return _suite


_runner = unittest.TextTestRunner()
_runner.run(_suite())
