"""Tests for the codecs module; expected values were produced by CPython 3.10.13."""
load("@stdlib//codecs", codecs="codecs")
load("@stdlib//unittest", unittest="unittest")
load("@vendor//asserts", asserts="asserts")


def _test_decode():
    asserts.assert_that(codecs.decode(b"\xff", "latin-1")).is_equal_to("\u00ff")
    asserts.assert_that(codecs.decode(b"\xe9", "Latin_1")).is_equal_to("\u00e9")
    asserts.assert_that(codecs.decode(b"\xe9", "latin1")).is_equal_to("\u00e9")
    asserts.assert_that(codecs.decode(b"\xe9", "ISO-8859-1")).is_equal_to("\u00e9")
    asserts.assert_that(codecs.decode(b"\xe9", "iso8859_1")).is_equal_to("\u00e9")
    asserts.assert_that(codecs.decode(b"\xe9", "L1")).is_equal_to("\u00e9")
    asserts.assert_fails(lambda: codecs.decode(b"a\xe9", "ascii"), "^'ascii'\\ codec\\ can't\\ decode\\ byte\\ 0xe9\\ in\\ position\\ 1:\\ ordinal\\ not\\ in\\ range\\(128\\)$")
    asserts.assert_fails(lambda: codecs.decode(b"a\xe9", "US-ASCII"), "^'ascii'\\ codec\\ can't\\ decode\\ byte\\ 0xe9\\ in\\ position\\ 1:\\ ordinal\\ not\\ in\\ range\\(128\\)$")
    asserts.assert_that(codecs.decode(b"a\xe9", "ascii", "replace")).is_equal_to("a\ufffd")
    asserts.assert_that(codecs.decode(b"a\xe9", "ascii", "ignore")).is_equal_to("a")
    asserts.assert_that(codecs.decode(b"a\xe9\xea", "ascii", "backslashreplace")).is_equal_to("a\\xe9\\xea")
    asserts.assert_that(codecs.decode(b"\xff\xfea\x00", "utf-16")).is_equal_to("a")
    asserts.assert_that(codecs.decode(b"\xfe\xff\x00a", "utf-16")).is_equal_to("a")
    asserts.assert_that(codecs.decode(b"a\x00b\x00", "utf-16")).is_equal_to("ab")
    asserts.assert_that(codecs.decode(b"\x00a", "utf-16-be")).is_equal_to("a")
    asserts.assert_that(codecs.decode(b"a\x00", "UTF-16LE")).is_equal_to("a")
    asserts.assert_fails(lambda: codecs.decode(b"x", "nope"), "^unknown\\ encoding:\\ nope$")
    asserts.assert_fails(lambda: codecs.decode(b"x", "ISO_8891_1"), "^unknown\\ encoding:\\ ISO_8891_1$")
    asserts.assert_that(codecs.decode(b"\x80", "cp1252")).is_equal_to("\u20ac")
    asserts.assert_that(codecs.decode(b"\x80", "windows-1252")).is_equal_to("\u20ac")
    asserts.assert_fails(lambda: codecs.decode(b"\x81", "cp1252"), "^'charmap'\\ codec\\ can't\\ decode\\ byte\\ 0x81\\ in\\ position\\ 0:\\ character\\ maps\\ to\\ <undefined>$")
    asserts.assert_that(codecs.decode(b"caf\xc3\xa9", "utf8")).is_equal_to("caf\u00e9")
    asserts.assert_that(codecs.decode(b"caf\xc3\xa9", "UTF_8")).is_equal_to("caf\u00e9")
    asserts.assert_that(codecs.decode(b"\xed\xa0\x80x", "UTF8", "replace")).is_equal_to("\ufffd\ufffd\ufffdx")
    asserts.assert_that(codecs.decode(b"\xf0\x9f\x98", "utf8", "replace")).is_equal_to("\ufffd")
    asserts.assert_fails(lambda: codecs.decode(b"a\xe2\x82b", "utf8"), "^'utf\\-8'\\ codec\\ can't\\ decode\\ bytes\\ in\\ position\\ 1\\-2:\\ invalid\\ continuation\\ byte$")
    asserts.assert_fails(lambda: codecs.decode(b"\xff", "utf8"), "^'utf\\-8'\\ codec\\ can't\\ decode\\ byte\\ 0xff\\ in\\ position\\ 0:\\ invalid\\ start\\ byte$")
    asserts.assert_fails(lambda: codecs.decode(b"a\xe2\x82", "utf8"), "^'utf\\-8'\\ codec\\ can't\\ decode\\ bytes\\ in\\ position\\ 1\\-2:\\ unexpected\\ end\\ of\\ data$")
    asserts.assert_that(codecs.decode(b"\xc0\xaf", "utf8", "replace")).is_equal_to("\ufffd\ufffd")
    asserts.assert_that(codecs.decode(b"\xc0\xaf", "utf8", "ignore")).is_equal_to("")
    asserts.assert_that(codecs.decode(b"\xc1\x81", "cp500")).is_equal_to("Aa")
    asserts.assert_fails(lambda: codecs.decode(b"\xff", "utf8", "bogus"), "^decoding\\ with\\ 'utf8'\\ codec\\ failed\\ \\(LookupError:\\ unknown\\ error\\ handler\\ name\\ 'bogus'\\)$")
    asserts.assert_that(codecs.decode(b"a", "utf8", "bogus")).is_equal_to("a")
    asserts.assert_that(codecs.decode(b"\x82\xa0", "shift_jis")).is_equal_to("\u3042")


def _test_encode():
    asserts.assert_that(codecs.encode("\u00e9", "latin-1")).is_equal_to(b"\xe9")
    asserts.assert_that(codecs.encode("\u00e9", "iso-8859-1")).is_equal_to(b"\xe9")
    asserts.assert_fails(lambda: codecs.encode("\u20ac", "latin-1"), "^'latin\\-1'\\ codec\\ can't\\ encode\\ character\\ '\\\\u20ac'\\ in\\ position\\ 0:\\ ordinal\\ not\\ in\\ range\\(256\\)$")
    asserts.assert_fails(lambda: codecs.encode("a\u20ac\u20acb", "ascii"), "^'ascii'\\ codec\\ can't\\ encode\\ characters\\ in\\ position\\ 1\\-2:\\ ordinal\\ not\\ in\\ range\\(128\\)$")
    asserts.assert_that(codecs.encode("a\u20acb", "ascii", "replace")).is_equal_to(b"\x61\x3f\x62")
    asserts.assert_that(codecs.encode("a\u20acb", "ascii", "ignore")).is_equal_to(b"\x61\x62")
    asserts.assert_that(codecs.encode("a\u20acb\u00e9", "ascii", "backslashreplace")).is_equal_to(b"\x61\x5c\x75\x32\x30\x61\x63\x62\x5c\x78\x65\x39")
    asserts.assert_that(codecs.encode("a\u20acb", "ascii", "xmlcharrefreplace")).is_equal_to(b"\x61\x26\x23\x38\x33\x36\x34\x3b\x62")
    asserts.assert_that(codecs.encode("a\u20acb", "ascii", "namereplace")).is_equal_to(b"\x61\x5c\x4e\x7b\x45\x55\x52\x4f\x20\x53\x49\x47\x4e\x7d\x62")
    asserts.assert_that(codecs.encode("ab", "utf-16")).is_equal_to(b"\xff\xfe\x61\x00\x62\x00")
    asserts.assert_that(codecs.encode("ab", "utf-16-be")).is_equal_to(b"\x00\x61\x00\x62")
    asserts.assert_that(codecs.encode("ab", "utf-32")).is_equal_to(b"\xff\xfe\x00\x00\x61\x00\x00\x00\x62\x00\x00\x00")
    asserts.assert_that(codecs.encode("\u20ac", "cp1252")).is_equal_to(b"\x80")
    asserts.assert_fails(lambda: codecs.encode("\u0100", "cp1252"), "^'charmap'\\ codec\\ can't\\ encode\\ character\\ '\\\\u0100'\\ in\\ position\\ 0:\\ character\\ maps\\ to\\ <undefined>$")
    asserts.assert_fails(lambda: codecs.encode("x", "nope"), "^unknown\\ encoding:\\ nope$")
    asserts.assert_that(codecs.encode("A", "cp500")).is_equal_to(b"\xc1")
    asserts.assert_fails(lambda: codecs.encode("a\U0001F63Fb", "ascii"), "^'ascii'\\ codec\\ can't\\ encode\\ character\\ '\\\\U0001f63f'\\ in\\ position\\ 1:\\ ordinal\\ not\\ in\\ range\\(128\\)$")
    asserts.assert_that(codecs.encode("a\U0001F63Fb", "ascii", "replace")).is_equal_to(b"\x61\x3f\x62")
    asserts.assert_fails(lambda: codecs.encode("\u20ac", "ascii", "bogus"), "^encoding\\ with\\ 'ascii'\\ codec\\ failed\\ \\(LookupError:\\ unknown\\ error\\ handler\\ name\\ 'bogus'\\)$")
    asserts.assert_that(codecs.encode("\u3042", "shift_jis")).is_equal_to(b"\x82\xa0")
    asserts.assert_that(codecs.encode("\u00e9", "utf-8")).is_equal_to(b"\xc3\xa9")


def _test_utf_8_decode():
    asserts.assert_that(codecs.utf_8_decode(b"a\xe2\x82")).is_equal_to(("a", 1))
    asserts.assert_fails(lambda: codecs.utf_8_decode(b"a\xe2\x82", "strict", True), "^'utf\\-8'\\ codec\\ can't\\ decode\\ bytes\\ in\\ position\\ 1\\-2:\\ unexpected\\ end\\ of\\ data$")
    asserts.assert_that(codecs.utf_8_decode(b"a\xe2\x82", "replace", True)).is_equal_to(("a\ufffd", 3))
    asserts.assert_that(codecs.utf_8_decode(b"caf\xc3\xa9")).is_equal_to(("caf\u00e9", 5))


def _test_known_codecs():
    # each codec (and one alias of each) that Larky maps to a Java charset
    asserts.assert_that(codecs.encode("abc", "ascii")).is_equal_to(b"\x61\x62\x63")
    asserts.assert_that(codecs.decode(b"\x61\x62\x63", "ascii")).is_equal_to("abc")
    asserts.assert_that(codecs.encode("abc", "latin_1")).is_equal_to(b"\x61\x62\x63")
    asserts.assert_that(codecs.decode(b"\x61\x62\x63", "latin_1")).is_equal_to("abc")
    asserts.assert_that(codecs.encode("abc", "utf_8")).is_equal_to(b"\x61\x62\x63")
    asserts.assert_that(codecs.decode(b"\x61\x62\x63", "utf_8")).is_equal_to("abc")
    asserts.assert_that(codecs.encode("abc", "utf_16")).is_equal_to(b"\xff\xfe\x61\x00\x62\x00\x63\x00")
    asserts.assert_that(codecs.decode(b"\xff\xfe\x61\x00\x62\x00\x63\x00", "utf_16")).is_equal_to("abc")
    asserts.assert_that(codecs.encode("abc", "utf_16_le")).is_equal_to(b"\x61\x00\x62\x00\x63\x00")
    asserts.assert_that(codecs.decode(b"\x61\x00\x62\x00\x63\x00", "utf_16_le")).is_equal_to("abc")
    asserts.assert_that(codecs.encode("abc", "utf_16_be")).is_equal_to(b"\x00\x61\x00\x62\x00\x63")
    asserts.assert_that(codecs.decode(b"\x00\x61\x00\x62\x00\x63", "utf_16_be")).is_equal_to("abc")
    asserts.assert_that(codecs.encode("abc", "utf_32")).is_equal_to(b"\xff\xfe\x00\x00\x61\x00\x00\x00\x62\x00\x00\x00\x63\x00\x00\x00")
    asserts.assert_that(codecs.decode(b"\xff\xfe\x00\x00\x61\x00\x00\x00\x62\x00\x00\x00\x63\x00\x00\x00", "utf_32")).is_equal_to("abc")
    asserts.assert_that(codecs.encode("abc", "utf_32_le")).is_equal_to(b"\x61\x00\x00\x00\x62\x00\x00\x00\x63\x00\x00\x00")
    asserts.assert_that(codecs.decode(b"\x61\x00\x00\x00\x62\x00\x00\x00\x63\x00\x00\x00", "utf_32_le")).is_equal_to("abc")
    asserts.assert_that(codecs.encode("abc", "utf_32_be")).is_equal_to(b"\x00\x00\x00\x61\x00\x00\x00\x62\x00\x00\x00\x63")
    asserts.assert_that(codecs.decode(b"\x00\x00\x00\x61\x00\x00\x00\x62\x00\x00\x00\x63", "utf_32_be")).is_equal_to("abc")
    asserts.assert_that(codecs.encode("abc", "cp1250")).is_equal_to(b"\x61\x62\x63")
    asserts.assert_that(codecs.decode(b"\x61\x62\x63", "cp1250")).is_equal_to("abc")
    asserts.assert_that(codecs.encode("abc", "cp1251")).is_equal_to(b"\x61\x62\x63")
    asserts.assert_that(codecs.decode(b"\x61\x62\x63", "cp1251")).is_equal_to("abc")
    asserts.assert_that(codecs.encode("abc", "cp1252")).is_equal_to(b"\x61\x62\x63")
    asserts.assert_that(codecs.decode(b"\x61\x62\x63", "cp1252")).is_equal_to("abc")
    asserts.assert_that(codecs.encode("abc", "cp1253")).is_equal_to(b"\x61\x62\x63")
    asserts.assert_that(codecs.decode(b"\x61\x62\x63", "cp1253")).is_equal_to("abc")
    asserts.assert_that(codecs.encode("abc", "cp1254")).is_equal_to(b"\x61\x62\x63")
    asserts.assert_that(codecs.decode(b"\x61\x62\x63", "cp1254")).is_equal_to("abc")
    asserts.assert_that(codecs.encode("abc", "cp1255")).is_equal_to(b"\x61\x62\x63")
    asserts.assert_that(codecs.decode(b"\x61\x62\x63", "cp1255")).is_equal_to("abc")
    asserts.assert_that(codecs.encode("abc", "cp1256")).is_equal_to(b"\x61\x62\x63")
    asserts.assert_that(codecs.decode(b"\x61\x62\x63", "cp1256")).is_equal_to("abc")
    asserts.assert_that(codecs.encode("abc", "cp1257")).is_equal_to(b"\x61\x62\x63")
    asserts.assert_that(codecs.decode(b"\x61\x62\x63", "cp1257")).is_equal_to("abc")
    asserts.assert_that(codecs.encode("abc", "cp1258")).is_equal_to(b"\x61\x62\x63")
    asserts.assert_that(codecs.decode(b"\x61\x62\x63", "cp1258")).is_equal_to("abc")
    asserts.assert_that(codecs.encode("abc", "iso8859_2")).is_equal_to(b"\x61\x62\x63")
    asserts.assert_that(codecs.decode(b"\x61\x62\x63", "iso8859_2")).is_equal_to("abc")
    asserts.assert_that(codecs.encode("abc", "iso8859_3")).is_equal_to(b"\x61\x62\x63")
    asserts.assert_that(codecs.decode(b"\x61\x62\x63", "iso8859_3")).is_equal_to("abc")
    asserts.assert_that(codecs.encode("abc", "iso8859_4")).is_equal_to(b"\x61\x62\x63")
    asserts.assert_that(codecs.decode(b"\x61\x62\x63", "iso8859_4")).is_equal_to("abc")
    asserts.assert_that(codecs.encode("abc", "iso8859_5")).is_equal_to(b"\x61\x62\x63")
    asserts.assert_that(codecs.decode(b"\x61\x62\x63", "iso8859_5")).is_equal_to("abc")
    asserts.assert_that(codecs.encode("abc", "iso8859_6")).is_equal_to(b"\x61\x62\x63")
    asserts.assert_that(codecs.decode(b"\x61\x62\x63", "iso8859_6")).is_equal_to("abc")
    asserts.assert_that(codecs.encode("abc", "iso8859_7")).is_equal_to(b"\x61\x62\x63")
    asserts.assert_that(codecs.decode(b"\x61\x62\x63", "iso8859_7")).is_equal_to("abc")
    asserts.assert_that(codecs.encode("abc", "iso8859_8")).is_equal_to(b"\x61\x62\x63")
    asserts.assert_that(codecs.decode(b"\x61\x62\x63", "iso8859_8")).is_equal_to("abc")
    asserts.assert_that(codecs.encode("abc", "iso8859_9")).is_equal_to(b"\x61\x62\x63")
    asserts.assert_that(codecs.decode(b"\x61\x62\x63", "iso8859_9")).is_equal_to("abc")
    asserts.assert_that(codecs.encode("abc", "iso8859_13")).is_equal_to(b"\x61\x62\x63")
    asserts.assert_that(codecs.decode(b"\x61\x62\x63", "iso8859_13")).is_equal_to("abc")
    asserts.assert_that(codecs.encode("abc", "iso8859_15")).is_equal_to(b"\x61\x62\x63")
    asserts.assert_that(codecs.decode(b"\x61\x62\x63", "iso8859_15")).is_equal_to("abc")
    asserts.assert_that(codecs.encode("abc", "iso8859_16")).is_equal_to(b"\x61\x62\x63")
    asserts.assert_that(codecs.decode(b"\x61\x62\x63", "iso8859_16")).is_equal_to("abc")
    asserts.assert_that(codecs.encode("abc", "cp037")).is_equal_to(b"\x81\x82\x83")
    asserts.assert_that(codecs.decode(b"\x81\x82\x83", "cp037")).is_equal_to("abc")
    asserts.assert_that(codecs.encode("abc", "cp437")).is_equal_to(b"\x61\x62\x63")
    asserts.assert_that(codecs.decode(b"\x61\x62\x63", "cp437")).is_equal_to("abc")
    asserts.assert_that(codecs.encode("abc", "cp500")).is_equal_to(b"\x81\x82\x83")
    asserts.assert_that(codecs.decode(b"\x81\x82\x83", "cp500")).is_equal_to("abc")
    asserts.assert_that(codecs.encode("abc", "cp737")).is_equal_to(b"\x61\x62\x63")
    asserts.assert_that(codecs.decode(b"\x61\x62\x63", "cp737")).is_equal_to("abc")
    asserts.assert_that(codecs.encode("abc", "cp775")).is_equal_to(b"\x61\x62\x63")
    asserts.assert_that(codecs.decode(b"\x61\x62\x63", "cp775")).is_equal_to("abc")
    asserts.assert_that(codecs.encode("abc", "cp850")).is_equal_to(b"\x61\x62\x63")
    asserts.assert_that(codecs.decode(b"\x61\x62\x63", "cp850")).is_equal_to("abc")
    asserts.assert_that(codecs.encode("abc", "cp852")).is_equal_to(b"\x61\x62\x63")
    asserts.assert_that(codecs.decode(b"\x61\x62\x63", "cp852")).is_equal_to("abc")
    asserts.assert_that(codecs.encode("abc", "cp855")).is_equal_to(b"\x61\x62\x63")
    asserts.assert_that(codecs.decode(b"\x61\x62\x63", "cp855")).is_equal_to("abc")
    asserts.assert_that(codecs.encode("abc", "cp857")).is_equal_to(b"\x61\x62\x63")
    asserts.assert_that(codecs.decode(b"\x61\x62\x63", "cp857")).is_equal_to("abc")
    asserts.assert_that(codecs.encode("abc", "cp858")).is_equal_to(b"\x61\x62\x63")
    asserts.assert_that(codecs.decode(b"\x61\x62\x63", "cp858")).is_equal_to("abc")
    asserts.assert_that(codecs.encode("abc", "cp862")).is_equal_to(b"\x61\x62\x63")
    asserts.assert_that(codecs.decode(b"\x61\x62\x63", "cp862")).is_equal_to("abc")
    asserts.assert_that(codecs.encode("abc", "cp866")).is_equal_to(b"\x61\x62\x63")
    asserts.assert_that(codecs.decode(b"\x61\x62\x63", "cp866")).is_equal_to("abc")
    asserts.assert_that(codecs.encode("abc", "cp874")).is_equal_to(b"\x61\x62\x63")
    asserts.assert_that(codecs.decode(b"\x61\x62\x63", "cp874")).is_equal_to("abc")
    asserts.assert_that(codecs.encode("abc", "cp1026")).is_equal_to(b"\x81\x82\x83")
    asserts.assert_that(codecs.decode(b"\x81\x82\x83", "cp1026")).is_equal_to("abc")
    asserts.assert_that(codecs.encode("abc", "cp1140")).is_equal_to(b"\x81\x82\x83")
    asserts.assert_that(codecs.decode(b"\x81\x82\x83", "cp1140")).is_equal_to("abc")
    asserts.assert_that(codecs.encode("abc", "koi8_r")).is_equal_to(b"\x61\x62\x63")
    asserts.assert_that(codecs.decode(b"\x61\x62\x63", "koi8_r")).is_equal_to("abc")
    asserts.assert_that(codecs.encode("abc", "koi8_u")).is_equal_to(b"\x61\x62\x63")
    asserts.assert_that(codecs.decode(b"\x61\x62\x63", "koi8_u")).is_equal_to("abc")
    asserts.assert_that(codecs.encode("abc", "mac_roman")).is_equal_to(b"\x61\x62\x63")
    asserts.assert_that(codecs.decode(b"\x61\x62\x63", "mac_roman")).is_equal_to("abc")
    asserts.assert_that(codecs.encode("abc", "shift_jis")).is_equal_to(b"\x61\x62\x63")
    asserts.assert_that(codecs.decode(b"\x61\x62\x63", "shift_jis")).is_equal_to("abc")
    asserts.assert_that(codecs.encode("abc", "cp932")).is_equal_to(b"\x61\x62\x63")
    asserts.assert_that(codecs.decode(b"\x61\x62\x63", "cp932")).is_equal_to("abc")
    asserts.assert_that(codecs.encode("abc", "euc_jp")).is_equal_to(b"\x61\x62\x63")
    asserts.assert_that(codecs.decode(b"\x61\x62\x63", "euc_jp")).is_equal_to("abc")
    asserts.assert_that(codecs.encode("abc", "euc_kr")).is_equal_to(b"\x61\x62\x63")
    asserts.assert_that(codecs.decode(b"\x61\x62\x63", "euc_kr")).is_equal_to("abc")
    asserts.assert_that(codecs.encode("abc", "cp949")).is_equal_to(b"\x61\x62\x63")
    asserts.assert_that(codecs.decode(b"\x61\x62\x63", "cp949")).is_equal_to("abc")
    asserts.assert_that(codecs.encode("abc", "gb2312")).is_equal_to(b"\x61\x62\x63")
    asserts.assert_that(codecs.decode(b"\x61\x62\x63", "gb2312")).is_equal_to("abc")
    asserts.assert_that(codecs.encode("abc", "gbk")).is_equal_to(b"\x61\x62\x63")
    asserts.assert_that(codecs.decode(b"\x61\x62\x63", "gbk")).is_equal_to("abc")
    asserts.assert_that(codecs.encode("abc", "gb18030")).is_equal_to(b"\x61\x62\x63")
    asserts.assert_that(codecs.decode(b"\x61\x62\x63", "gb18030")).is_equal_to("abc")
    asserts.assert_that(codecs.encode("abc", "big5")).is_equal_to(b"\x61\x62\x63")
    asserts.assert_that(codecs.decode(b"\x61\x62\x63", "big5")).is_equal_to("abc")
    asserts.assert_that(codecs.encode("abc", "cp950")).is_equal_to(b"\x61\x62\x63")
    asserts.assert_that(codecs.decode(b"\x61\x62\x63", "cp950")).is_equal_to("abc")
    asserts.assert_that(codecs.encode("abc", "iso2022_jp")).is_equal_to(b"\x61\x62\x63")
    asserts.assert_that(codecs.decode(b"\x61\x62\x63", "iso2022_jp")).is_equal_to("abc")
    asserts.assert_that(codecs.encode("abc", "iso2022_kr")).is_equal_to(b"\x61\x62\x63")
    asserts.assert_that(codecs.decode(b"\x61\x62\x63", "iso2022_kr")).is_equal_to("abc")
    asserts.assert_that(codecs.encode("abc", "tis_620")).is_equal_to(b"\x61\x62\x63")
    asserts.assert_that(codecs.decode(b"\x61\x62\x63", "tis_620")).is_equal_to("abc")


def _testsuite():
    _suite = unittest.TestSuite()
    _suite.addTest(unittest.FunctionTestCase(_test_decode))
    _suite.addTest(unittest.FunctionTestCase(_test_encode))
    _suite.addTest(unittest.FunctionTestCase(_test_utf_8_decode))
    _suite.addTest(unittest.FunctionTestCase(_test_known_codecs))
    return _suite


_runner = unittest.TextTestRunner()
_runner.run(_testsuite())
