load("@stdlib//unittest", "unittest")
load("@vendor//asserts", "asserts")
load("@vgs//http/request", "VGSHttpRequest")

load("@stdlib//json","json")
load("@vendor//jose/jwe", jwe="jwe")

def process(input, ctx):
    jwk_data = json.loads('{"kty":"RSA","kid":"qfNlZYnIBmF_1JyVr14wlu34pDNQ9ggEjC6HiDQkDks","n":"uo80-yn_zR3vrRWFunyLTm7NFKO0aWFH1LsdkRPm62w13AA1btO89IxncW56L8qIAX7xBlCt92TB4mVnGEzWUbPLyn-OPyg5sgltsoAjFcYeFc0uvp0-iRMse4udjwk0YqrCgAOwlcL5IQu9KmqH3KdH8o1Um9QtoBxHe4ACWMdu8I2Xktm2vi076opkT2AquqLXRzD4gujAALgTMnGmBmNSqhKa2GK4iSjqUSTkYL6wF_OtPfdmlrlri_qaChRk-kK1VzIDk8jG_-I8d47_Pdln7FmADhO1O4_-4IoOiM1ESarNkO46aFV4I4xcFWvh0JnJQIoSwgPoqCPH3v7NiQ","e":"AQAB","alg":"RSA-OAEP-256","use":"enc"}')

    jwe_data = "{\"user\":{\"name\":{\"first_name\":\"Test\",\"last_name\":\"Test\"},\"address\":{\"street\":\"Street1\",\"street2\":\"Apt.#1\",\"city\":\"NewYork\",\"region\":\"NY\",\"postal_code\":\"12345\",\"country\":\"US\"},\"phone_number\":\"+15174242424\"},\"card\":{\"number\":\"4242424242424242\",\"expiration\":\"07/26\",\"cvv\":\"012\"}}"

    jwe_string = jwe.encrypt(jwe_data, jwk_data, 'A256GCM', jwk_data.get("alg"), None, None, jwk_data.get("kid"))

    input.body = jwe_string
    return input

def test_process():
    # keys below are not real (generated by randomizer)
    input = VGSHttpRequest("https://test.com/post", data=b"", headers={}, method='POST')
    response = process(input, None)
    print("YYYYYYYY")
    print(response.body)

def _testsuite():
    _suite = unittest.TestSuite()
    _suite.addTest(unittest.FunctionTestCase(test_process))
    return _suite

_runner = unittest.TextTestRunner()
_runner.run(_testsuite())