;; Writes "<argc> <argv_buf_size> <environ_count> <environ_buf_size> <fd_prestat_get(3) errno>\n"
;; followed by argv[0] (without its NUL). With argv ["module"], no environment and no preopens the
;; output is "1 7 0 0 8\nmodule" (8 is EBADF).
(module
  (import "wasi_snapshot_preview1" "args_sizes_get" (func $args_sizes_get (param i32 i32) (result i32)))
  (import "wasi_snapshot_preview1" "args_get" (func $args_get (param i32 i32) (result i32)))
  (import "wasi_snapshot_preview1" "environ_sizes_get" (func $environ_sizes_get (param i32 i32) (result i32)))
  (import "wasi_snapshot_preview1" "fd_prestat_get" (func $fd_prestat_get (param i32 i32) (result i32)))
  (import "wasi_snapshot_preview1" "fd_write" (func $fd_write (param i32 i32 i32 i32) (result i32)))
  (memory (export "memory") 1)
  (data (i32.const 300) " \n")
  (func $write (param $ptr i32) (param $len i32)
    (i32.store (i32.const 0) (local.get $ptr))
    (i32.store (i32.const 4) (local.get $len))
    (drop (call $fd_write (i32.const 1) (i32.const 0) (i32.const 1) (i32.const 16))))
  (func $write_u32 (param $v i32)
    (local $p i32)
    (local.set $p (i32.const 2048))
    (loop $digit
      (local.set $p (i32.sub (local.get $p) (i32.const 1)))
      (i32.store8 (local.get $p) (i32.add (i32.const 48) (i32.rem_u (local.get $v) (i32.const 10))))
      (local.set $v (i32.div_u (local.get $v) (i32.const 10)))
      (br_if $digit (local.get $v)))
    (call $write (local.get $p) (i32.sub (i32.const 2048) (local.get $p))))
  (func $space (call $write (i32.const 300) (i32.const 1)))
  (func (export "_start")
    (local $argc i32)
    (local $argv_size i32)
    (local $argv0 i32)
    (local $len i32)
    (drop (call $args_sizes_get (i32.const 400) (i32.const 404)))
    (local.set $argc (i32.load (i32.const 400)))
    (local.set $argv_size (i32.load (i32.const 404)))
    (drop (call $environ_sizes_get (i32.const 408) (i32.const 412)))
    (call $write_u32 (local.get $argc))
    (call $space)
    (call $write_u32 (local.get $argv_size))
    (call $space)
    (call $write_u32 (i32.load (i32.const 408)))
    (call $space)
    (call $write_u32 (i32.load (i32.const 412)))
    (call $space)
    (call $write_u32 (call $fd_prestat_get (i32.const 3) (i32.const 416)))
    (call $write (i32.const 301) (i32.const 1))
    ;; argv pointers at 4096, argv strings at 8192
    (if (i32.and (i32.ge_u (local.get $argc) (i32.const 1))
                 (i32.le_u (local.get $argv_size) (i32.const 4096)))
      (then
        (drop (call $args_get (i32.const 4096) (i32.const 8192)))
        (local.set $argv0 (i32.load (i32.const 4096)))
        (block $end
          (loop $scan
            (br_if $end (i32.eqz (i32.load8_u (i32.add (local.get $argv0) (local.get $len)))))
            (local.set $len (i32.add (local.get $len) (i32.const 1)))
            (br $scan)))
        (call $write (local.get $argv0) (local.get $len))))))
